#! /bin/sh
# kcminputrc Mouse cursorTheme 'breeze_cursors'
kcminputrc_mouse_cursortheme=breeze_cursors
# kcminputrc Mouse cursorSize ''
kcminputrc_mouse_cursorsize=48
# ksplashrc KSplash Theme Breeze
ksplashrc_ksplash_theme=None
# ksplashrc KSplash Engine KSplashQML
ksplashrc_ksplash_engine=none
# kdeglobals KScreen ScreenScaleFactors ''
kdeglobals_kscreen_screenscalefactors='DSI1=1.8;DP1=1.0;DP2=1.0;HDMI1=1.0;HDMI2=1.0;VIRTUAL1=1.0;'
# kcmfonts General forceFontDPI 0
kcmfonts_general_forcefontdpi=180
